[ds.mysql]
    dsn = "root:toor@tcp(localhost:3306)/maxtrack"
    interval = 10 # cache interval in minutes
[ds.redis]
	host = ":6379"
	fprefix = "fleet"
    tprefix = "tracker"
    uprefix = "user"
[srv]
	port = "0.0.0.0:8080"
[log]
	path = "info.log"
[errors]
    [errors.NotExistInCache]
    msg = "such record does not exist"

[defaults]
   lng= 69.245811
   lat= 41.293964
   direction = 1
   speed  = 0
   sat = 0
   ignition = 2
   gsmSignal = 0
   battery  = 0
   seat  = 0
   batteryLvl = 0
   fuel = 0
   fuelVal = 0
   muAdditional = "0"
   action = 2
   time = "2015-01-01 12:00:00"
