[ds.mysql]
    dsn = "root:toor@tcp(localhost:3306)/maxtrack"
    interval = 10 # cache interval in minutes
[ds.redis]
	host = ":6379"
	fprefix = "fleet"
    tprefix = "tracker"
[srv]
	port = ":1234"
[log]
	path = "info.log"
